(() => {
    const config = window.TEAMSIGNUPS_CONFIG || {};
    const endpoint = typeof config.googleScriptUrl === "string" ? config.googleScriptUrl.trim() : "";
    const useSupabase = config.storageProvider === "supabase";
    const container = document.getElementById("public-event-list");
    const status = document.getElementById("sync-status");
    const overlay = document.getElementById("loadingOverlay");
    const countdown = document.getElementById("volunteer-countdown");
    if (!container || (!useSupabase && !endpoint)) { if (status) { status.textContent = "Unable to load signup form."; status.dataset.type = "error"; } return; }
    function setStatus(message, type = "info") { if (!status) return; status.hidden = !message; status.textContent = message; status.dataset.type = type; }
    function showLoading(message) { if (!overlay) return; const text = overlay.querySelector(".loading-text"); if (text) text.textContent = message; overlay.classList.remove("hidden"); }
    function hideLoading() { if (overlay) overlay.classList.add("hidden"); }
    function supabaseHeaders() { return { apikey: config.supabaseAnonKey, Authorization: `Bearer ${config.supabaseAnonKey}`, "Content-Type": "application/json" }; }
    async function loadEvents() { const response = useSupabase ? await fetch(`${config.supabaseUrl}/rest/v1/rpc/get_public_events`, { method: "POST", headers: supabaseHeaders(), body: "{}", cache: "no-store" }) : await fetch(endpoint, { method: "GET", cache: "no-store" }); if (!response.ok) throw new Error(`Unable to load events (${response.status})`); const payload = JSON.parse(await response.text()); return Array.isArray(payload.events) ? payload.events : []; }
    async function saveEvents(events) { const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "text/plain;charset=utf-8" }, body: JSON.stringify({ events }) }); if (!response.ok) throw new Error("Unable to save signup"); }
    async function claimCoachSlot(eventId, slotId, signup) { const response = await fetch(`${config.supabaseUrl}/rest/v1/rpc/claim_coach_slot`, { method: "POST", headers: supabaseHeaders(), body: JSON.stringify({ p_event_id: String(eventId), p_slot_id: String(slotId), p_signup: signup }) }); if (!response.ok) { const result = await response.json().catch(() => ({})); throw new Error(result.message || "Unable to save signup"); } }
    async function notifySignup(event, slot, signup) { if (!config.emailNotificationUrl) return false; try { const response = await fetch(config.emailNotificationUrl, { method: "POST", headers: { "Content-Type": "text/plain;charset=utf-8" }, body: JSON.stringify({ action: "supabaseSignupEmail", claim: { eventId: event.id, eventTitle: event.title || "", eventDate: event.date || "", slotId: slot.id, slotName: slot.name || "", person: signup } }) }); if (!response.ok) return false; const result = await response.json(); return result.ok === true && !result.mailError; } catch (error) { console.error("Signup email notification failed:", error); return false; } }
    function formatDate(rawDate) { const date = new Date(`${rawDate}T00:00:00`); return date.toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }); }
    function uid() { return Math.random().toString(36).slice(2, 10); }
    function publicName(firstName, lastName) { const firstInitial = String(firstName || "").trim().charAt(0).toUpperCase(); const safeLastName = String(lastName || "").trim(); return `${firstInitial}. ${safeLastName}`.trim(); }
    function normalizeEmail(value) { return String(value || "").trim().toLowerCase(); }
    function validEmail(value) { const email = normalizeEmail(value); return /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(email); }
    function phoneDigits(value) { let digits = String(value || "").replace(/\D/g, ""); if (digits.length === 11 && digits.startsWith("1")) digits = digits.slice(1); return digits; }
    function normalizePhone(value) { return phoneDigits(value); }
    function formatPhone(value) { const digits = phoneDigits(value); if (digits.length !== 10) return null; return `(${digits.slice(0,3)}) ${digits.slice(3,6)}-${digits.slice(6)}`; }
    function setupPhoneInput(input) { if (!input) return; input.setAttribute("inputmode", "tel"); input.setAttribute("maxlength", "16"); input.placeholder = "(717) 555-1234"; input.addEventListener("blur", () => { const formatted = formatPhone(input.value); if (formatted) input.value = formatted; }); }
    function findDuplicate(events, email, phone) { const targetEmail = normalizeEmail(email); const targetPhone = normalizePhone(phone); for (const event of events) for (const slot of (event.slots || [])) for (const person of (slot.claimedBy || [])) { const emailMatch = targetEmail && normalizeEmail(person.email) === targetEmail; const phoneMatch = targetPhone && normalizePhone(person.phone) === targetPhone; if (emailMatch || phoneMatch) return { person, event, slot, emailMatch, phoneMatch }; } return null; }
    function updateCountdown(events) {
        if (!countdown) return;
        let total = 0, filled = 0;
        for (const event of events) for (const slot of (event.slots || [])) { const count = Math.max(0, Number(slot.count || 0)); total += count; filled += Math.min(count, Array.isArray(slot.claimedBy) ? slot.claimedBy.length : 0); }
        if (!total) { countdown.hidden = true; return; }
        const remaining = Math.max(0, total - filled); const percent = Math.min(100, Math.round((filled / total) * 100));
        const title = document.getElementById("volunteer-countdown-title"); const subtitle = document.getElementById("volunteer-countdown-subtitle"); const meta = document.getElementById("volunteer-countdown-meta"); const bar = document.getElementById("volunteer-progress-bar"); const track = countdown.querySelector('[role="progressbar"]');
        countdown.classList.remove("urgent", "close", "complete");
        if (remaining === 0) { countdown.classList.add("complete"); title.textContent = "🎉 ALL VOLUNTEER POSITIONS FILLED! 🎉"; subtitle.textContent = "Thank you, CV Soccer families — we did it!"; }
        else if (remaining <= Math.max(2, Math.ceil(total * 0.2))) { countdown.classList.add("close"); title.textContent = `🔥 ONLY ${remaining} ${remaining === 1 ? "VOLUNTEER" : "VOLUNTEERS"} TO GO! 🔥`; subtitle.textContent = "We’re almost there — can you help us finish strong?"; }
        else { countdown.classList.add("urgent"); title.textContent = `🚨 WE STILL NEED ${remaining} ${remaining === 1 ? "VOLUNTEER" : "VOLUNTEERS"}! 🚨`; subtitle.textContent = "Every signup helps us form teams and get kids on the field."; }
        meta.textContent = `${filled} of ${total} positions filled • ${percent}% complete`; bar.style.width = `${percent}%`; if (track) track.setAttribute("aria-valuenow", String(percent)); countdown.hidden = false;
    }
    function render(events) {
        updateCountdown(events);
        container.replaceChildren(); const sorted = [...events].sort((a,b) => Number(a.order ?? 0) - Number(b.order ?? 0)); if (!sorted.length) { container.innerHTML = '<p class="empty">No events available yet.</p>'; return; }
        sorted.forEach((event) => { const article = document.createElement("article"); article.className = "event"; article.innerHTML = `<h3>${event.title}</h3><div class="event-meta">Teams due by ${formatDate(event.date)}</div><p>${event.description || "No description provided."}</p><div class="slots-wrap"></div>`; const slotsWrap = article.querySelector(".slots-wrap");
            (event.slots || []).forEach((slot) => { const claimedBy = Array.isArray(slot.claimedBy) ? slot.claimedBy : []; const isFull = Number(slot.count || 0) - claimedBy.length <= 0; const slotNode = document.createElement("div"); slotNode.className = isFull ? "slot position-full" : "slot"; const names = claimedBy.map((person) => person.publicName).filter(Boolean).join(", "); const signupForm = isFull ? "" : `<form class="signup-form"><div class="fields-grid"><input name="firstName" placeholder="First name" required /><input name="lastName" placeholder="Last name" required /><input name="email" type="email" placeholder="name@example.com" required /><input name="phone" placeholder="(717) 555-1234" inputmode="tel" maxlength="16" required /><label>Shirt size<select name="shirtSize" required><option value="" selected disabled>Select shirt size</option><option value="S">S</option><option value="M">M</option><option value="L">L</option><option value="XL">XL</option><option value="XXL">XXL</option></select></label><label>Request access to <a href="https://soccerhandbook.com/" target="_blank" rel="noopener noreferrer" title="Open The Soccer Handbook website">The Soccer Handbook</a>?<select name="handbookAccess" required><option value="N" selected>N</option><option value="Y">Y</option></select></label><input name="notes" placeholder="Any notes (optional)" /></div><button type="submit">Sign up</button></form>`; slotNode.innerHTML = `<div><strong>${slot.name}</strong><br /><small>${isFull ? "FULL" : `${claimedBy.length}/${slot.count} filled`}</small>${names ? `<p class="signed-up-list">Signed up: ${names}</p>` : ""}</div>${signupForm}`;
                const form = slotNode.querySelector("form"); if (form) { setupPhoneInput(form.querySelector('input[name="phone"]')); form.addEventListener("submit", async (eventSubmit) => { eventSubmit.preventDefault(); if (config.previewMode) { setStatus("Preview only — no signup was submitted.", "info"); return; } const formData = new FormData(form); const email = normalizeEmail(formData.get("email")); if (!validEmail(email)) { setStatus("Please enter a valid email address, such as name@example.com.", "error"); form.querySelector('input[name="email"]').focus(); return; } const formattedPhone = formatPhone(formData.get("phone")); if (!formattedPhone) { setStatus("Please enter a valid 10-digit U.S. phone number.", "error"); form.querySelector('input[name="phone"]').focus(); return; } showLoading("Saving signup...");
                        try { const latestEvents = await loadEvents(); const latestEvent = latestEvents.find((item) => String(item.id) === String(event.id)); const latestSlot = latestEvent?.slots?.find((item) => String(item.id) === String(slot.id)); if (!latestEvent || !latestSlot) throw new Error("Position no longer exists"); latestSlot.claimedBy = Array.isArray(latestSlot.claimedBy) ? latestSlot.claimedBy : []; if (latestSlot.claimedBy.length >= Number(latestSlot.count || 0)) throw new Error("This position has just been filled"); const firstName = String(formData.get("firstName") || "").trim(); const lastName = String(formData.get("lastName") || "").trim(); const duplicate = findDuplicate(latestEvents, email, formattedPhone); if (duplicate) { hideLoading(); const matchType = duplicate.emailMatch && duplicate.phoneMatch ? "email address and phone number" : duplicate.emailMatch ? "email address" : "phone number"; const existingName = duplicate.person.publicName || publicName(duplicate.person.firstName, duplicate.person.lastName) || "another volunteer"; const proceed = window.confirm(`Duplicate warning: This ${matchType} is already used by ${existingName} for ${duplicate.event.title} – ${duplicate.slot.name}.\n\nDo you still want to add this signup?`); if (!proceed) { setStatus("Signup not added. The email or phone number is already in use.", "info"); return; } showLoading("Saving signup..."); } const signup = { id: uid(), firstName, lastName, email, phone: formattedPhone, shirtSize: String(formData.get("shirtSize") || ""), handbookAccess: String(formData.get("handbookAccess") || "N"), notes: String(formData.get("notes") || "").trim(), publicName: publicName(firstName, lastName) }; let emailSent = true; if (useSupabase) { await claimCoachSlot(event.id, slot.id, signup); emailSent = await notifySignup(latestEvent, latestSlot, signup); } else { latestSlot.claimedBy.push(signup); await saveEvents(latestEvents); } setStatus(emailSent ? "Thanks for volunteering! Your signup was saved and a confirmation email was sent." : "Your signup was saved, but the confirmation email could not be sent. CV Soccer has your signup.", emailSent ? "ok" : "info"); render(await loadEvents()); } catch (error) { setStatus(error instanceof Error ? error.message : "Unable to save signup.", "error"); } finally { hideLoading(); }
                    }); }
                slotsWrap.appendChild(slotNode); }); container.appendChild(article); });
    }
    (async () => { try { setStatus("Loading volunteer signups... This may take several minutes depending on your connection.", "info"); render(await loadEvents()); setStatus("", "ok"); } catch (error) { setStatus("The volunteer database is currently unavailable. Please try again shortly.", "error"); container.innerHTML = '<p class="empty">Unable to load coaching positions.</p>'; } })();
})();
