(() => {
    const adminContainer = document.getElementById("admin-event-list");
    if (!adminContainer) return;
    function phoneDigits(value) { let digits = String(value || "").replace(/\D/g, ""); if (digits.length === 11 && digits.startsWith("1")) digits = digits.slice(1); return digits; }
    function formatPhone(value) { const digits = phoneDigits(value); if (digits.length !== 10) return null; return `(${digits.slice(0, 3)}) ${digits.slice(3, 6)}-${digits.slice(6)}`; }
    function validEmail(value) { return /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(String(value || "").trim().toLowerCase()); }
    function setupPhoneInput(input) { if (!input) return; input.setAttribute("inputmode", "tel"); input.setAttribute("maxlength", "16"); input.placeholder = "(717) 555-1234"; input.addEventListener("blur", () => { const formatted = formatPhone(input.value); if (formatted) input.value = formatted; }); }
    function ensureDialog() {
        let dialog = document.getElementById("editVolunteerDialog"); if (dialog) return dialog;
        dialog = document.createElement("dialog"); dialog.id = "editVolunteerDialog"; dialog.className = "modal";
        dialog.innerHTML = `<form id="editVolunteerForm" class="modal-card"><h3>Edit volunteer</h3><input type="hidden" name="eventId" /><input type="hidden" name="slotId" /><input type="hidden" name="personId" /><label>First name<input name="firstName" required /></label><label>Last name<input name="lastName" required /></label><label>Email<input name="email" type="email" placeholder="name@example.com" required /></label><label>Phone<input name="phone" required /></label><label>Notes<textarea name="notes" rows="3"></textarea></label><div class="modal-actions"><button type="button" id="editVolunteerCancel" class="secondary">Cancel</button><button type="submit" class="primary">Save changes</button></div></form>`;
        document.body.appendChild(dialog); dialog.querySelector("#editVolunteerCancel").addEventListener("click", () => dialog.close()); dialog.querySelector("#editVolunteerForm").addEventListener("submit", saveVolunteer); setupPhoneInput(dialog.querySelector('input[name="phone"]')); return dialog;
    }
    async function openVolunteerEditor(button) {
        try { const events = await loadEvents(); const eventId = String(button.dataset.eventId || ""); const slotId = String(button.dataset.slotId || ""); const personId = String(button.dataset.personId || ""); const event = events.find((item) => String(item.id) === eventId); const slot = event?.slots?.find((item) => String(item.id) === slotId); const person = slot?.claimedBy?.find((item) => String(item.id) === personId); if (!person) throw new Error("Volunteer not found"); const dialog = ensureDialog(); const form = dialog.querySelector("#editVolunteerForm"); form.eventId.value = eventId; form.slotId.value = slotId; form.personId.value = personId; form.firstName.value = person.firstName || ""; form.lastName.value = person.lastName || ""; form.email.value = person.email || ""; form.phone.value = formatPhone(person.phone) || person.phone || ""; form.notes.value = person.notes || ""; dialog.showModal(); } catch (error) { window.alert(error instanceof Error ? error.message : "Unable to edit volunteer."); }
    }
    async function saveVolunteer(event) {
        event.preventDefault(); const form = event.currentTarget; const dialog = form.closest("dialog"); const email = String(form.email.value || "").trim().toLowerCase(); const formattedPhone = formatPhone(form.phone.value);
        if (!validEmail(email)) { window.alert("Please enter a valid email address, such as name@example.com."); form.email.focus(); return; }
        if (!formattedPhone) { window.alert("Please enter a valid 10-digit U.S. phone number."); form.phone.focus(); return; }
        try { showLoading("Updating volunteer..."); const events = await loadEvents(); const eventObj = events.find((item) => String(item.id) === String(form.eventId.value)); const slot = eventObj?.slots?.find((item) => String(item.id) === String(form.slotId.value)); const person = slot?.claimedBy?.find((item) => String(item.id) === String(form.personId.value)); if (!person) throw new Error("Volunteer not found"); const firstName = String(form.firstName.value || "").trim(); const lastName = String(form.lastName.value || "").trim(); person.firstName = firstName; person.lastName = lastName; person.email = email; person.phone = formattedPhone; person.notes = String(form.notes.value || "").trim(); person.publicName = publicDisplayName(firstName, lastName); await saveEvents(events); dialog.close(); setActionStatus("Volunteer information updated.", "ok"); await renderAdminPage(); } catch (error) { window.alert(error instanceof Error ? error.message : "Unable to update volunteer."); } finally { await hideLoading(); }
    }
    function addEditButtons() { adminContainer.querySelectorAll(".remove-signup").forEach((removeButton) => { const cell = removeButton.closest("td"); if (!cell || cell.querySelector(".edit-signup")) return; const editButton = document.createElement("button"); editButton.type = "button"; editButton.className = "small edit-signup"; editButton.textContent = "Edit"; editButton.dataset.eventId = removeButton.dataset.eventId || ""; editButton.dataset.slotId = removeButton.dataset.slotId || ""; editButton.dataset.personId = removeButton.dataset.personId || ""; editButton.style.marginRight = "6px"; editButton.style.width = "auto"; removeButton.style.width = "auto"; editButton.addEventListener("click", () => openVolunteerEditor(editButton)); cell.insertBefore(editButton, removeButton); }); }
    const observer = new MutationObserver(addEditButtons); observer.observe(adminContainer, { childList: true, subtree: true }); addEditButtons();
})();
